---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question. 
  
### my answer     
  i went to and graduated from east side high school. i feel that i was equally okay in both math and English but i struggled more in English because i wasn't very good at the writing aspect of it. math was easier to understand because everything was explained and i just had to solve whatever the problem was.

     

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer
 i have a chrome book and an iPad at home that i can use for this at home. If i were t rate myself on a scale from 1-10 based on my computer skills id rate myself a 4-5/10 because im not terrible at using a computer and can usually eventually figure it out but id prefer doing things on paper.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  i am okay with being referred to as angelica
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  id like to be successful in life, id like to go for my phd although i am unaware what subject id like to get it in.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  ive only ever been to mexico once, but other than that ive never been out of the country. id like to go to Rome, Spain Greece and Sweden. i have never been in the military, id like to go into the medical branch
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




